; Generated by design-integration/render_installer.mjs — do not edit; re-run the renderer.
!define KF_W 576
!define KF_H 400
!define KF_SLOT_BG 0xEEE7D9 ; the grained linen's mean colour
!define KF_WELCOME_CTA "160 212 256 44"
!define KF_WELCOME_VER "88 276 400 16"
!define KF_WELCOME_PATH "88 294 400 16"
!define KF_WELCOME_ALT "188 318 200 22"
!define KF_PLANTING_BAR "160 244 256 6"
!define KF_PLANTING_STATUS "88 262 400 16"
!define KF_PLANTED_OPEN "148 236 280 22"
!define KF_PLANTED_CTA "160 274 256 44"
!define KF_UPROOT_WIPE "128 236 320 22"
!define KF_UPROOT_CTA "160 274 256 44"
!define KF_UPROOT_KEEP "188 330 200 22"
!define KF_UPROOTING_BAR "160 244 256 6"
!define KF_UPROOTING_STATUS "88 262 400 16"
!define KF_UPROOTED_CTA "160 248 256 44"
