"""Bitmaps, fonts and icons for the Android home-screen widgets (Phone Widgets.dc.html), written
into app/native/android/res/ (CI copies that over the generated project). Run from the repo root:

    python design-integration/render_widget_res.py

- no fonts: a launcher inflates widgets in a restricted context, where TextView ignores an app's
  font resources — the widgets use the phone's serif / serif-monospace / cursive instead.
- icons: the kit's stroke icons (src/components/icons/kf) → VectorDrawables, white, tinted per view.
- art: the garden PNGs the widgets show, scaled to ~3× their widget size (WebP).
- grain + tape: the paper grain tile and the goal card's tape (RemoteViews can't blend or rotate).
"""
import io
import math
import random
import re
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
RES = ROOT / 'app/native/android/res'
ICONS = ROOT / 'app/src/components/icons/kf'
ART = ROOT / 'app/public/ds/assets'

# ── icons: SVG (stroke, 24 box) → VectorDrawable ──
def rect_path(x, y, w, h, r):
    if not r:
        return f'M{x},{y}h{w}v{h}h{-w}z'
    return (f'M{x + r},{y}h{w - 2 * r}a{r},{r} 0 0 1 {r},{r}v{h - 2 * r}a{r},{r} 0 0 1 {-r},{r}'
            f'h{-(w - 2 * r)}a{r},{r} 0 0 1 {-r},{-r}v{-(h - 2 * r)}a{r},{r} 0 0 1 {r},{-r}z')


def circle_path(cx, cy, r):
    return f'M{cx - r},{cy}a{r},{r} 0 1 0 {2 * r},0a{r},{r} 0 1 0 {-2 * r},0z'


def attrs(tag):
    return {k: v for k, v in re.findall(r'([\w-]+)="([^"]*)"', tag)}


draw_dir = RES / 'drawable'
draw_dir.mkdir(parents=True, exist_ok=True)
ICON_NAMES = ['check', 'plus', 'mic', 'focus', 'star', 'stop', 'review', 'pickdate', 'routines', 'inbox', 'offline', 'journal', 'send']
for name in ICON_NAMES:
    svg = (ICONS / f'kf-{name}.svg').read_text()
    root = attrs(re.search(r'<svg[^>]*>', svg).group(0))
    paths = []
    for tag, body in re.findall(r'<(path|rect|circle)([^>]*)>', svg):
        a = attrs(body)
        if tag == 'path':
            d = a['d']
        elif tag == 'rect':
            d = rect_path(*(float(a.get(k, 0)) for k in ('x', 'y', 'width', 'height', 'rx')))
        else:
            d = circle_path(*(float(a[k]) for k in ('cx', 'cy', 'r')))
        paths.append(f'    <path android:pathData="{d}" android:strokeColor="#FFFFFFFF" android:strokeWidth="{root.get("stroke-width", "1.6")}"'
                     f' android:strokeLineCap="round" android:strokeLineJoin="round" />')
    (draw_dir / f'kfw_ic_{name}.xml').write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by design-integration/render_widget_res.py from src/components/icons/kf. -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android" android:width="24dp" android:height="24dp"'
        ' android:viewportWidth="24" android:viewportHeight="24">\n' + '\n'.join(paths) + '\n</vector>\n')

# ── art: ~3× the widget's height, WebP with alpha ──
nodpi = RES / 'drawable-nodpi'
nodpi.mkdir(parents=True, exist_ok=True)
for path, h in {
    'clover/four_leaf': 34, 'clover/seedling': 56, 'fern/coil': 56, 'vine/flowering': 92, 'vine/sprouting': 34,
    'hydrangea/medium': 70, 'hydrangea/light': 46, 'hydrangea/zero': 64, 'daisy/morning': 74, 'daisy/evening': 74,
    'daisy/midday': 40, 'wisteria/p80': 82, 'wisteria/p40': 40, 'envelope/front': 34, 'cherry/bloom': 66,
    'seal/intact': 48, 'tools/pen': 24,
}.items():
    im = Image.open(ART / f'{path}.png').convert('RGBA')
    target = h * 3
    if im.height > target:
        im = im.resize((round(im.width * target / im.height), target), Image.LANCZOS)
    im.save(nodpi / f"kfw_art_{path.replace('/', '_')}.webp", 'WEBP', quality=86, method=6)

# ── grain: the app's noise (effects.css --noise-url: brown, alpha ≤ 0.05) at the widgets' 0.45 ──
random.seed(7)
g = Image.new('RGBA', (96, 96))
g.putdata([(46, 41, 31, int(random.randint(0, 255) * 0.05 * 0.45 * 2.2)) for _ in range(96 * 96)])
g.save(nodpi / 'kfw_grain.png')

# ── the dashed hairline's tile: 3dp on, 3dp off (tinted line-dashed in drawable/kfw_dash.xml) ──
d = Image.new('RGBA', (18, 3))
d.putdata([(255, 255, 255, 255 if x < 9 else 0) for _ in range(3) for x in range(18)])
d.save(nodpi / 'kfw_dash_tile.png')

# ── tape: 58×15dp, gold 38%, white stripes every 4dp, turned −2° (rendered at 3×) ──
for folder, gold in (('drawable-nodpi', (127, 100, 40)), ('drawable-night-nodpi', (228, 195, 107))):
    s = 3
    t = Image.new('RGBA', (58 * s, 15 * s), (*gold, round(255 * 0.38)))
    d = ImageDraw.Draw(t)
    for x in range(0, 58 * s, 8 * s):
        d.rectangle([x, 0, x + 4 * s - 1, 15 * s], fill=(min(255, gold[0] + 90), min(255, gold[1] + 90), min(255, gold[2] + 90), round(255 * 0.55)))
    t = t.rotate(2, resample=Image.BICUBIC, expand=True)
    (RES / folder).mkdir(parents=True, exist_ok=True)
    t.save(RES / folder / 'kfw_tape.png')
print('widget resources written to', RES)
